### ISSUE TITLE
Running other examples. towards running mass_spring.py

### ISSUE THREAD

**Issue by nijeshu** [yuanming-hu/taichi#211]
When i try to run python3 projects/examples/examples_extra/vector.py
i get errors like: 
Loading module mpm
Traceback (most recent call last):
  File "projects/examples/examples_extra/vector.py", line 4, in <module>
    x = ti.Matrix(2, 2, ti.i32)
AttributeError: module 'taichi' has no attribute 'Matrix'
or 
[T 10/03/19 23:35:16.846] [logging.cpp:Logger@67] Taichi core started. Thread ID = 21115
Loading module mpm
Traceback (most recent call last):
  File "projects/examples/examples_extra/difftaichi/mass_spring.py", line 14, in <module>
    real = ti.f32
AttributeError: module 'taichi' has no attribute 'f32'

Am i missing something?

**Comment by yuanming-hu** [comment]
I believe this is resolved with the pip wheel.
