### ISSUE TITLE
torch example throwing error

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#260]
Example: https://github.com/yuanming-hu/taichi/blob/1eda9ed02bb0cc39394fdc7bf81948f7faa9caeb/examples/pytorch_tensor_ad.py

throws the following error:

```
[Release mode]
Using CUDA Device [0]: Quadro RTX 8000
Device Compute Capability: 7.5
[T 11/15/19 14:12:19.713] [logging.cpp:Logger@68] Taichi core started. Thread ID = 7218
[Taichi version 0.0.87, cuda 10.0, commit 8aa4f054]
[I 11/15/19 14:12:23.626] [taichi_llvm_context.cpp:TaichiLLVMContext@59] Creating llvm context for arch: x86_64
Materializing layout...
[I 11/15/19 14:12:23.682] [codegen_llvm_x86.cpp:global_optimize_module_x86_64@93] Global optimization time: 46.284 ms
[I 11/15/19 14:12:23.684] [struct_llvm.cpp:operator()@264] Allocating data structure of size 512
Initializing runtime with 6 elements
Runtime initialized.
[I 11/15/19 14:12:23.697] [taichi_llvm_context.cpp:TaichiLLVMContext@59] Creating llvm context for arch: cuda
Compiling kernel ker_0_...
Warning: numpy array arg supports 1D and f32 only for now
Traceback (most recent call last):
  File "torch_test.py", line 52, in <module>
    sqr(X).sum().backward()
  File "torch_test.py", line 33, in forward
    ti.from_torch(x, inp)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/torch_io.py", line 12, in from_torch
    ker.materialize()
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 189, in materialize
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 189, in <lambda>
    taichi_kernel = taichi_kernel.define(lambda: compiled())
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/torch_io.py", line 11, in ker
    
NameError: name 'expr' is not defined
```

**Comment by yuanming-hu** [comment]
Sorry about the bug. Fixed in the latest commit and will release the next version in a couple of hours.

**Comment by aespielberg** [comment]
Thanks.  Should I be regularly updating my taichi installation?

**Comment by yuanming-hu** [comment]
Yeah, that's recommended.
