### ISSUE TITLE
Recipe for backpropagating through pytorch?

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#270]
I am trying to integrate the current simulator with pytorch.  The purpose is to have neural network controllers.

Script is below.  I am a little confused by three things:

1. I have to manually declare a loss.  If I try to set the loss as just y[0] in ti.Tape, I get an error.  Is this a bug?

2. What is the functional difference between 

`x = scalar(); ti.root.dense(ti.i, n).place(x)`

and

`x = vec(); ti.root.place(x) `

The former works; however, the latter causes problems.

3. The backward pass here does not work, giving the stack trace I've put at the very bottom.  What is the correct way in general to do this backprop?  My case is a little different than the pytorch test you have written: Rather than sandwich taichi code between pytorch, I want to sandiwch pytorch between taichi.

```
import taichi as ti
import numpy as np
import torch
import torch.nn as nn
from math_tools import *
import IPython


ti.cfg.arch = ti.cuda

x = scalar()
y = scalar()
loss = scalar()


class MLP(nn.Module):
  def __init__(self, in_shape, out_shape, n_hidden=64):
    super(MLP, self).__init__()
    self.hidden1 = nn.Linear(in_shape, n_hidden)
    self.hidden2 = nn.Linear(n_hidden, n_hidden)
    self.out = nn.Linear(n_hidden, out_shape)
    self.relu = nn.ReLU()
    self.tanh = nn.Tanh()

  def forward(self, x):
    x = self.relu(self.hidden1(x))
    x = self.tanh(self.hidden2(x))
    x = self.out(x)
    return x

n = 2
m = 4
controller = MLP(n, m)
controller.cuda(torch.device('cuda:0'))



@ti.layout
def place():
  ti.root.dense(ti.i, n).place(x)
  ti.root.dense(ti.i, n).place(y)
  ti.root.place(loss)
  ti.root.lazy_grad()

@ti.complex_kernel
def forward():
  inp = torch.zeros_like(x)
  ti.to_torch(x, inp)
  actuation = controller(inp)
  ti.from_torch(y, actuation)
  loss[None] = y[0]


@ti.complex_kernel_grad(forward)
def forward_grad():
  inp = torch.zeros_like(x)
  ti.to_torch(x, inp)
  actuation = controller(inp)
  ti.from_torch(y, actuation)
  y.grad()

state = np.array([1.0, 2.0, 3.0, 4.0])

for i in range(n):
  x[i] = state[i]


with ti.Tape(loss):
  forward()
```

The error this code gives is:
```

[Release mode]
Using CUDA Device [0]: Quadro RTX 8000
Device Compute Capability: 7.5
[T 11/19/19 16:26:02.583] [logging.cpp:Logger@68] Taichi core started. Thread ID = 3133
[Taichi version 0.1.2, cuda 10.0, commit e809655d]
[I 11/19/19 16:26:06.912] [taichi_llvm_context.cpp:TaichiLLVMContext@59] Creating llvm context for arch: x86_64
Materializing layout...
[I 11/19/19 16:26:06.990] [codegen_llvm_x86.cpp:global_optimize_module_x86_64@93] Global optimization time: 65.6619 ms
[I 11/19/19 16:26:06.992] [struct_llvm.cpp:operator()@264] Allocating data structure of size 40
Initializing runtime with 9 elements
Runtime initialized.
[I 11/19/19 16:26:07.008] [taichi_llvm_context.cpp:TaichiLLVMContext@59] Creating llvm context for arch: cuda
[I 11/19/19 16:26:07.202] [codegen_llvm_x86.cpp:global_optimize_module_x86_64@93] Global optimization time: 28.1539 ms
[I 11/19/19 16:26:07.304] [llvm_jit_ptx.cpp:compile@287] PTX size: 2.86KB
[I 11/19/19 16:26:07.399] [llvm_jit_ptx.cpp:compile@287] PTX size: 2.86KB
[I 11/19/19 16:26:07.470] [llvm_jit_ptx.cpp:compile@287] PTX size: 0.64KB
[I 11/19/19 16:26:07.540] [codegen_llvm_x86.cpp:global_optimize_module_x86_64@93] Global optimization time: 17.6539 ms
[I 11/19/19 16:26:07.611] [codegen_llvm_x86.cpp:global_optimize_module_x86_64@93] Global optimization time: 17.1521 ms
Traceback (most recent call last):
  File "torch_test2.py", line 73, in <module>
    forward()
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 128, in decorated
    raise e
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 126, in decorated
    func(*args, **kwargs)
  File "torch_test2.py", line 51, in forward
    inp = torch.zeros_like(x)
TypeError: zeros_like() received an invalid combination of arguments - got (Expr), but expected one of:
 * (Tensor input, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Tensor input, bool requires_grad)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "torch_test2.py", line 73, in <module>
    forward()
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/tape.py", line 21, in __exit__
    self.grad()
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/tape.py", line 32, in grad
    func.grad(*args)
  File "/home/aespielberg2/anaconda3/lib/python3.7/site-packages/taichi/lang/__init__.py", line 138, in decorated
    func(*args, **kwargs)
  File "torch_test2.py", line 60, in forward_grad
    inp = torch.zeros_like(x)
TypeError: zeros_like() received an invalid combination of arguments - got (Expr), but expected one of:
 * (Tensor input, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Tensor input, bool requires_grad)

```

**Comment by yuanming-hu** [comment]
Hi Andy,

Thanks for the questions.

1. Loss must be a scalar tensor. If you want to use y[0], please define a kernel that copies y[0] to loss[None]

2. I know this can be confusing. 
`x = scalar(); ti.root.dense(ti.i, n).place(x)` gives you a 1D tensor of size (n,) of a scalar 
`x = vec(); ti.root.place(x)` gives you a 0D tesnor of size () of a vector

3. This is slightly complicated. Let me talk to you via hangouts about this.
